
blueprint:
  name: 除湿关闭
  description: 湿度低于70%关闭所在房间空调除湿模式
  domain: automation
  input:
    humidity_entity:
      name: humidity sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    climate_entity:
      name: climate
      selector:
        entity:
          domain: climate

mode: single

trigger:
  - platform: numeric_state
    entity_id: !input humidity_entity
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 70
condition:
  - condition: state
    entity_id: input_boolean.jia_zhong_wu_ren
    state: "off"
  - condition: state
    entity_id: !input climate_entity
    attribute: hvac_action
    state: drying
action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: "off"
    target:
      entity_id: !input climate_entity
